{
    "language": "node_js",
    "node_js": "8",
    "addons": [
        "mariadb": "10.3"
    ],
    "before_install": [
        "mysql -e 'CREATE DATABASE IF NOT EXISTS test;'"
    ],
    "script": [
        "npm run build",
        "npm run test"
    ]
}
