version: "3.4"

volumes:
  app:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local

services:
  web:
    build: .
    command: sh -c "sleep 5 && npm start"
    restart: always
    ports:
      - "3000:3000"
    image: crafting-database
    depends_on:
      - db
    environment:
      - SERVER_PORT=3000
      - WOW_CLIENT_ID
      - WOW_CLIENT_SECRET
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=cdb
      - DB_PASSWORD
      - DB_DATABASE=cdb
      - CONNECTED_REALMS
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:3000/api/auctions/lastUpdate"]
      start_period: 30s
    volumes:
      - app:/app
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USERNAME=cdb
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=cdb
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
